version: "3"
services:
  mysql:
    container_name: todo_app_db
    image: mysql:5.7
    platform: linux/x86_64
    volumes:
      - todo_app_data:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      MYSQL_DATABASE: todo_app
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - todo_app_network
    healthcheck:
      test: exit 0

  app:
    container_name: todo_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PW: root
      DB_NAME: todo_app
    networks:
      - todo_app_network
    ports:
      - "8080:8080"

networks:
  todo_app_network:
    driver: bridge

volumes:
  todo_app_data: {}